### ISSUE TITLE
What problem this project try to solve?

### ISSUE THREAD

**Issue by khotyn** [alibaba/cloud-native-app-initializer#13]
It seems that this project has no screenshot, no document, so what is the difference between this project and spring initializer? What problem this project try to solve?

By the way, this project could not run in Mac Apple Silicon, run `mvn compile -P install-yarn` got the following error:

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-yarn (install node and yarn) on project initializer-page: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
```

And there is also no docker image for Mac Apple Silicon.

**Comment by steverao** [comment]
This problem seems to be related to your system version, you can try [this reply](https://github.com/eirslett/frontend-maven-plugin/issues/952) to see if it can solve your problem. Because this is a tool project, we don't have as many feature documents as general open source. You can directly experience our products through [this website](https://start.aliyun.com/). For your problem about difference between with Spring initializr. In addition to dependency management capabilities, we also provide example codes related to the use of middleware, more specific, you can refer to our [introductory article](https://mp.weixin.qq.com/s/5hsrCfAdO7gBOJcT6fLpbg).

**Comment by steverao** [comment]
Long time without response and close first.
